"""
Music Database - Comprehensive Bollywood and Punjabi music database
with 20 artists and 15+ songs each for recommendation system
"""

# Database of artists with their genres and songs
artists_data = [
    {
        "id": "1",
        "name": "Arijit Singh",
        "genres": ["Bollywood", "Romantic", "Sufi", "Classical"],
        "songs": [
            {"id": "101", "title": "Tum Hi Ho", "duration": "4:22"},
            {"id": "102", "title": "Channa Mereya", "duration": "5:12"},
            {"id": "103", "title": "Agar Tum Saath Ho", "duration": "5:41"},
            {"id": "104", "title": "Kalank Title Track", "duration": "5:11"},
            {"id": "105", "title": "Raabta", "duration": "4:03"},
            {"id": "106", "title": "Ae Dil Hai Mushkil", "duration": "4:29"},
            {"id": "107", "title": "Gerua", "duration": "5:08"},
            {"id": "108", "title": "Phir Bhi Tumko Chahunga", "duration": "4:54"},
            {"id": "109", "title": "Shayad", "duration": "4:08"},
            {"id": "110", "title": "Khairiyat", "duration": "4:40"},
            {"id": "111", "title": "Mast Magan", "duration": "4:40"},
            {"id": "112", "title": "Nashe Si Chadh Gayi", "duration": "3:58"},
            {"id": "113", "title": "Laal Ishq", "duration": "5:41"},
            {"id": "114", "title": "Naina", "duration": "4:35"},
            {"id": "115", "title": "Hawayein", "duration": "4:50"},
            {"id": "116", "title": "Hamari Adhuri Kahani", "duration": "5:26"},
            {"id": "117", "title": "Enna Sona", "duration": "4:12"},
            {"id": "118", "title": "Bolna", "duration": "3:50"}
        ]
    },
    {
        "id": "2",
        "name": "Diljit Dosanjh",
        "genres": ["Punjabi", "Bhangra", "Pop", "Bollywood"],
        "songs": [
            {"id": "201", "title": "G.O.A.T.", "duration": "3:22"},
            {"id": "202", "title": "Patiala Peg", "duration": "4:12"},
            {"id": "203", "title": "Proper Patola", "duration": "3:46"},
            {"id": "204", "title": "Do You Know", "duration": "3:55"},
            {"id": "205", "title": "Vibe", "duration": "3:10"},
            {"id": "206", "title": "5 Taara", "duration": "3:18"},
            {"id": "207", "title": "Born to Shine", "duration": "3:29"},
            {"id": "208", "title": "Lover", "duration": "3:47"},
            {"id": "209", "title": "Laembadgini", "duration": "3:30"},
            {"id": "210", "title": "Clash", "duration": "3:26"},
            {"id": "211", "title": "High End", "duration": "3:09"},
            {"id": "212", "title": "Ikk Kudi", "duration": "4:20"},
            {"id": "213", "title": "Raat Di Gedi", "duration": "3:24"},
            {"id": "214", "title": "Putt Jatt Da", "duration": "3:20"},
            {"id": "215", "title": "Jind Mahi", "duration": "3:19"},
            {"id": "216", "title": "Sadda Move", "duration": "3:14"},
            {"id": "217", "title": "Ishq Di Baajiyaan", "duration": "4:10"}
        ]
    },
    {
        "id": "3",
        "name": "Neha Kakkar",
        "genres": ["Bollywood", "Pop", "Dance", "Indie Pop"],
        "songs": [
            {"id": "301", "title": "Dilbar", "duration": "3:44"},
            {"id": "302", "title": "Kala Chashma", "duration": "4:36"},
            {"id": "303", "title": "Aankh Marey", "duration": "3:29"},
            {"id": "304", "title": "Garmi", "duration": "2:41"},
            {"id": "305", "title": "O Saki Saki", "duration": "2:50"},
            {"id": "306", "title": "Mile Ho Tum Humko", "duration": "4:12"},
            {"id": "307", "title": "Coca Cola", "duration": "2:50"},
            {"id": "308", "title": "Yaad Piya Ki Aane Lagi", "duration": "3:38"},
            {"id": "309", "title": "Kar Gayi Chull", "duration": "3:00"},
            {"id": "310", "title": "Saki Saki", "duration": "3:34"},
            {"id": "311", "title": "Cheez Badi", "duration": "3:32"},
            {"id": "312", "title": "Maahi Ve", "duration": "3:52"},
            {"id": "313", "title": "Lamborghini", "duration": "3:44"},
            {"id": "314", "title": "Ek Toh Kum Zindagani", "duration": "3:12"},
            {"id": "315", "title": "Nikle Currant", "duration": "3:34"},
            {"id": "316", "title": "Gali Gali", "duration": "2:45"},
            {"id": "317", "title": "Puchda Hi Nahin", "duration": "3:58"}
        ]
    },
    {
        "id": "4",
        "name": "Sidhu Moose Wala",
        "genres": ["Punjabi", "Hip Hop", "Gangsta Rap", "Folk"],
        "songs": [
            {"id": "401", "title": "295", "duration": "4:30"},
            {"id": "402", "title": "So High", "duration": "3:28"},
            {"id": "403", "title": "Legend", "duration": "4:10"},
            {"id": "404", "title": "Just Listen", "duration": "4:07"},
            {"id": "405", "title": "The Last Ride", "duration": "4:29"},
            {"id": "406", "title": "Tochan", "duration": "4:35"},
            {"id": "407", "title": "Goat", "duration": "3:48"},
            {"id": "408", "title": "Burberry", "duration": "4:23"},
            {"id": "409", "title": "Tibeyan Da Putt", "duration": "4:12"},
            {"id": "410", "title": "Sohne Lagde", "duration": "4:01"},
            {"id": "411", "title": "Famous", "duration": "3:53"},
            {"id": "412", "title": "Jatt Da Muqabla", "duration": "3:25"},
            {"id": "413", "title": "Dear Mama", "duration": "4:30"},
            {"id": "414", "title": "Dollar", "duration": "3:49"},
            {"id": "415", "title": "Bambiha Bole", "duration": "5:13"},
            {"id": "416", "title": "G-Shit", "duration": "3:21"},
            {"id": "417", "title": "Racks and Rounds", "duration": "3:37"}
        ]
    },
    {
        "id": "5",
        "name": "Shreya Ghoshal",
        "genres": ["Bollywood", "Classical", "Romantic", "Folk"],
        "songs": [
            {"id": "501", "title": "Deewani Mastani", "duration": "5:06"},
            {"id": "502", "title": "Ghoomar", "duration": "4:21"},
            {"id": "503", "title": "Manwa Laage", "duration": "4:11"},
            {"id": "504", "title": "Teri Ore", "duration": "5:30"},
            {"id": "505", "title": "Param Sundari", "duration": "3:24"},
            {"id": "506", "title": "Bahara", "duration": "5:04"},
            {"id": "507", "title": "Agar Tum Mil Jao", "duration": "5:06"},
            {"id": "508", "title": "Jaadu Hai Nasha Hai", "duration": "5:55"},
            {"id": "509", "title": "Sunn Raha Hai", "duration": "6:30"},
            {"id": "510", "title": "Thodi Der", "duration": "4:03"},
            {"id": "511", "title": "Piyu Bole", "duration": "5:32"},
            {"id": "512", "title": "Pal Pal Har Pal", "duration": "5:55"},
            {"id": "513", "title": "Chikni Chameli", "duration": "5:03"},
            {"id": "514", "title": "Nagada Sang Dhol", "duration": "4:33"},
            {"id": "515", "title": "Ami Je Tomar", "duration": "4:12"},
            {"id": "516", "title": "Dola Re Dola", "duration": "6:35"},
            {"id": "517", "title": "Yeh Ishq Haaye", "duration": "4:44"}
        ]
    },
    {
        "id": "6",
        "name": "A.R. Rahman",
        "genres": ["Bollywood", "Fusion", "Classical", "Sufi", "Tamil"],
        "songs": [
            {"id": "601", "title": "Jai Ho", "duration": "5:19"},
            {"id": "602", "title": "Dil Se Re", "duration": "6:03"},
            {"id": "603", "title": "Kun Faya Kun", "duration": "7:42"},
            {"id": "604", "title": "Masakali", "duration": "4:48"},
            {"id": "605", "title": "Chaiyya Chaiyya", "duration": "6:54"},
            {"id": "606", "title": "Tum Ho", "duration": "5:12"},
            {"id": "607", "title": "Jiya Jale", "duration": "5:36"},
            {"id": "608", "title": "Tere Bina", "duration": "5:30"},
            {"id": "609", "title": "Khwaja Mere Khwaja", "duration": "6:56"},
            {"id": "610", "title": "Patakha Guddi", "duration": "5:55"},
            {"id": "611", "title": "Nadaan Parindey", "duration": "6:26"},
            {"id": "612", "title": "Tum Tak", "duration": "4:42"},
            {"id": "613", "title": "Luka Chuppi", "duration": "6:47"},
            {"id": "614", "title": "Taal Se Taal Mila", "duration": "5:12"},
            {"id": "615", "title": "Kabhi Neem Neem", "duration": "6:38"},
            {"id": "616", "title": "O Saya", "duration": "3:32"},
            {"id": "617", "title": "Rehna Tu", "duration": "6:52"},
            {"id": "618", "title": "Raanjhanaa", "duration": "4:04"}
        ]
    },
    {
        "id": "7",
        "name": "Guru Randhawa",
        "genres": ["Punjabi", "Pop", "Dance", "Hip Hop"],
        "songs": [
            {"id": "701", "title": "Lahore", "duration": "3:39"},
            {"id": "702", "title": "High Rated Gabru", "duration": "3:33"},
            {"id": "703", "title": "Suit Suit", "duration": "3:12"},
            {"id": "704", "title": "Morni Banke", "duration": "3:04"},
            {"id": "705", "title": "Slowly Slowly", "duration": "3:39"},
            {"id": "706", "title": "Dance Meri Rani", "duration": "3:23"},
            {"id": "707", "title": "Made in India", "duration": "3:28"},
            {"id": "708", "title": "Naach Meri Rani", "duration": "3:28"},
            {"id": "709", "title": "Crazy Habibi", "duration": "3:30"},
            {"id": "710", "title": "Ishare Tere", "duration": "3:24"},
            {"id": "711", "title": "Lagdi Lahore Di", "duration": "3:41"},
            {"id": "712", "title": "Black", "duration": "3:10"},
            {"id": "713", "title": "Baby Girl", "duration": "3:06"},
            {"id": "714", "title": "Surma Surma", "duration": "3:12"},
            {"id": "715", "title": "Downtown", "duration": "3:14"},
            {"id": "716", "title": "Fashion", "duration": "3:33"},
            {"id": "717", "title": "Daaru Wargi", "duration": "3:32"}
        ]
    },
    {
        "id": "8",
        "name": "Honey Singh",
        "genres": ["Hip Hop", "Rap", "Punjabi", "Party", "EDM"],
        "songs": [
            {"id": "801", "title": "Brown Rang", "duration": "3:39"},
            {"id": "802", "title": "Blue Eyes", "duration": "3:40"},
            {"id": "803", "title": "Angreji Beat", "duration": "3:51"},
            {"id": "804", "title": "Desi Kalakaar", "duration": "4:10"},
            {"id": "805", "title": "Chaar Botal Vodka", "duration": "3:50"},
            {"id": "806", "title": "Love Dose", "duration": "3:37"},
            {"id": "807", "title": "Sunny Sunny", "duration": "3:43"},
            {"id": "808", "title": "Lungi Dance", "duration": "3:43"},
            {"id": "809", "title": "Party All Night", "duration": "3:47"},
            {"id": "810", "title": "One Bottle Down", "duration": "3:01"},
            {"id": "811", "title": "Dheere Dheere", "duration": "3:32"},
            {"id": "812", "title": "Birthday Bash", "duration": "3:58"},
            {"id": "813", "title": "Dope Shope", "duration": "3:39"},
            {"id": "814", "title": "High Heels", "duration": "3:36"},
            {"id": "815", "title": "Care Ni Karda", "duration": "3:13"},
            {"id": "816", "title": "First Kiss", "duration": "3:24"},
            {"id": "817", "title": "Raat Jashan Di", "duration": "3:00"}
        ]
    },
    {
        "id": "9",
        "name": "Badshah",
        "genres": ["Hip Hop", "Rap", "Punjabi", "Electronic", "Bollywood"],
        "songs": [
            {"id": "901", "title": "DJ Waley Babu", "duration": "3:16"},
            {"id": "902", "title": "Mercy", "duration": "2:44"},
            {"id": "903", "title": "Paagal", "duration": "2:40"},
            {"id": "904", "title": "Genda Phool", "duration": "3:29"},
            {"id": "905", "title": "Kar Gayi Chull", "duration": "3:33"},
            {"id": "906", "title": "Proper Patola", "duration": "3:46"},
            {"id": "907", "title": "Abhi Toh Party Shuru Hui Hai", "duration": "3:30"},
            {"id": "908", "title": "Wakhra Swag", "duration": "3:04"},
            {"id": "909", "title": "Garmi", "duration": "2:41"},
            {"id": "910", "title": "Kala Chashma", "duration": "4:36"},
            {"id": "911", "title": "Saturday Saturday", "duration": "3:42"},
            {"id": "912", "title": "She Move It Like", "duration": "2:48"},
            {"id": "913", "title": "Jugnu", "duration": "3:22"},
            {"id": "914", "title": "Let's Nacho", "duration": "4:12"},
            {"id": "915", "title": "Sooraj Dooba Hain", "duration": "4:15"},
            {"id": "916", "title": "Bandook", "duration": "3:12"},
            {"id": "917", "title": "Heartless", "duration": "3:18"}
        ]
    },
    {
        "id": "10",
        "name": "Atif Aslam",
        "genres": ["Bollywood", "Romantic", "Sufi", "Pakistani Pop", "Classical"],
        "songs": [
            {"id": "1001", "title": "Tera Hone Laga Hoon", "duration": "5:00"},
            {"id": "1002", "title": "Tu Jaane Na", "duration": "5:41"},
            {"id": "1003", "title": "Jeena Jeena", "duration": "3:52"},
            {"id": "1004", "title": "Pehli Nazar Mein", "duration": "4:38"},
            {"id": "1005", "title": "Woh Lamhe", "duration": "4:35"},
            {"id": "1006", "title": "O Saathi", "duration": "3:58"},
            {"id": "1007", "title": "Main Rang Sharbaton Ka", "duration": "4:33"},
            {"id": "1008", "title": "Dil Diyan Gallan", "duration": "4:20"},
            {"id": "1009", "title": "Tere Sang Yaara", "duration": "4:49"},
            {"id": "1010", "title": "Dekhte Dekhte", "duration": "4:01"},
            {"id": "1011", "title": "Be Intehaan", "duration": "4:25"},
            {"id": "1012", "title": "Piya O Re Piya", "duration": "4:48"},
            {"id": "1013", "title": "Tajdar-e-Haram", "duration": "8:50"},
            {"id": "1014", "title": "Dil Meri Na Sune", "duration": "3:36"},
            {"id": "1015", "title": "Darasal", "duration": "4:33"},
            {"id": "1016", "title": "Aadat", "duration": "4:22"},
            {"id": "1017", "title": "Tere Liye", "duration": "5:13"}
        ]
    },
    {
        "id": "11",
        "name": "Sunanda Sharma",
        "genres": ["Punjabi", "Folk", "Pop", "Traditional"],
        "songs": [
            {"id": "1101", "title": "Jaani Tera Naa", "duration": "3:05"},
            {"id": "1102", "title": "Morni", "duration": "3:22"},
            {"id": "1103", "title": "Sandal", "duration": "3:09"},
            {"id": "1104", "title": "Duji Vaar Pyar", "duration": "3:48"},
            {"id": "1105", "title": "Pagal Nahi Hona", "duration": "3:19"},
            {"id": "1106", "title": "Billi Akh", "duration": "3:12"},
            {"id": "1107", "title": "Jail", "duration": "3:15"},
            {"id": "1108", "title": "Barish Ki Jaaye", "duration": "3:29"},
            {"id": "1109", "title": "Jersey", "duration": "3:07"},
            {"id": "1110", "title": "Sakhiyaan", "duration": "3:02"},
            {"id": "1111", "title": "The Haryanvi Mashup", "duration": "3:12"},
            {"id": "1112", "title": "Billi Akh", "duration": "3:12"},
            {"id": "1113", "title": "Challa", "duration": "3:23"},
            {"id": "1114", "title": "Fan Banna", "duration": "3:05"},
            {"id": "1115", "title": "Valentine's Day", "duration": "3:00"},
            {"id": "1116", "title": "Waddi Gal", "duration": "2:53"}
        ]
    },
    {
        "id": "12",
        "name": "AP Dhillon",
        "genres": ["Punjabi", "Hip Hop", "Trap", "R&B"],
        "songs": [
            {"id": "1201", "title": "Brown Munde", "duration": "4:25"},
            {"id": "1202", "title": "Excuses", "duration": "2:56"},
            {"id": "1203", "title": "Insane", "duration": "3:44"},
            {"id": "1204", "title": "Summer High", "duration": "3:05"},
            {"id": "1205", "title": "Desires", "duration": "4:02"},
            {"id": "1206", "title": "Ma Belle", "duration": "2:54"},
            {"id": "1207", "title": "Majhail", "duration": "4:12"},
            {"id": "1208", "title": "Toxic", "duration": "3:01"},
            {"id": "1209", "title": "Saada Pyaar", "duration": "3:52"},
            {"id": "1210", "title": "Deadly", "duration": "3:08"},
            {"id": "1211", "title": "All Night", "duration": "2:29"},
            {"id": "1212", "title": "Free Smoke", "duration": "3:18"},
            {"id": "1213", "title": "Tere Te", "duration": "3:26"},
            {"id": "1214", "title": "Old School", "duration": "2:44"},
            {"id": "1215", "title": "Most Wanted", "duration": "3:12"},
            {"id": "1216", "title": "With You", "duration": "2:35"}
        ]
    },
    {
        "id": "13",
        "name": "Jubin Nautiyal",
        "genres": ["Bollywood", "Romantic", "Indie Pop", "Sufi"],
        "songs": [
            {"id": "1301", "title": "Raataan Lambiyan", "duration": "3:50"},
            {"id": "1302", "title": "Lut Gaye", "duration": "4:15"},
            {"id": "1303", "title": "Tum Hi Aana", "duration": "4:30"},
            {"id": "1304", "title": "Taaron Ke Shehar", "duration": "4:15"},
            {"id": "1305", "title": "Kinna Sona", "duration": "3:15"},
            {"id": "1306", "title": "Meri Aashiqui", "duration": "4:26"},
            {"id": "1307", "title": "Tujhe Kitna Chahne Lage", "duration": "4:44"},
            {"id": "1308", "title": "Dil Galti Kar Baitha Hai", "duration": "4:20"},
            {"id": "1309", "title": "Barsaat Ki Dhun", "duration": "3:58"},
            {"id": "1310", "title": "Bewafa Tera Masoom Chehra", "duration": "5:12"},
            {"id": "1311", "title": "Humnava Mere", "duration": "3:53"},
            {"id": "1312", "title": "Main Jis Din Bhulaa Du", "duration": "4:05"},
            {"id": "1313", "title": "Akh Lad Jaave", "duration": "3:22"},
            {"id": "1314", "title": "Chitthi", "duration": "5:12"},
            {"id": "1315", "title": "Khushi Jab Bhi Teri", "duration": "3:45"},
            {"id": "1316", "title": "Dil Chahte Ho", "duration": "4:28"}
        ]
    },
    {
        "id": "14",
        "name": "Karan Aujla",
        "genres": ["Punjabi", "Hip Hop", "Gangsta", "Pop"],
        "songs": [
            {"id": "1401", "title": "Don't Worry", "duration": "3:12"},
            {"id": "1402", "title": "Mexico", "duration": "3:28"},
            {"id": "1403", "title": "Chitta Kurta", "duration": "3:03"},
            {"id": "1404", "title": "Jhanjar", "duration": "3:22"},
            {"id": "1405", "title": "Sheikh", "duration": "3:04"},
            {"id": "1406", "title": "So Far", "duration": "3:18"},
            {"id": "1407", "title": "Adhiya", "duration": "3:11"},
            {"id": "1408", "title": "2 AM", "duration": "3:28"},
            {"id": "1409", "title": "Players", "duration": "3:06"},
            {"id": "1410", "title": "Facts", "duration": "2:32"},
            {"id": "1411", "title": "Softly", "duration": "2:47"},
            {"id": "1412", "title": "Let 'Em Play", "duration": "3:15"},
            {"id": "1413", "title": "Hukam", "duration": "3:28"},
            {"id": "1414", "title": "Lafaafe", "duration": "2:49"},
            {"id": "1415", "title": "Gangsta", "duration": "3:12"},
            {"id": "1416", "title": "Street Dreams", "duration": "3:17"}
        ]
    },
    {
        "id": "15",
        "name": "Sonu Nigam",
        "genres": ["Bollywood", "Classical", "Sufi", "Romantic", "Pop"],
        "songs": [
            {"id": "1501", "title": "Kal Ho Naa Ho", "duration": "5:21"},
            {"id": "1502", "title": "Suraj Hua Maddham", "duration": "7:08"},
            {"id": "1503", "title": "Abhi Mujh Mein Kahin", "duration": "6:04"},
            {"id": "1504", "title": "Main Agar Kahoon", "duration": "5:08"},
            {"id": "1505", "title": "Saathiya", "duration": "5:18"},
            {"id": "1506", "title": "Tumse Milke Dil Ka", "duration": "5:12"},
            {"id": "1507", "title": "Sandese Aate Hai", "duration": "7:12"},
            {"id": "1508", "title": "Deewana Tera", "duration": "5:32"},
            {"id": "1509", "title": "Satrangi Re", "duration": "7:25"},
            {"id": "1510", "title": "Sapna Jahan", "duration": "5:08"},
            {"id": "1511", "title": "Yeh Dil Deewana", "duration": "5:51"},
            {"id": "1512", "title": "Main Hoon Na", "duration": "7:45"},
            {"id": "1513", "title": "Piyu Bole", "duration": "5:32"},
            {"id": "1514", "title": "Tanhaji", "duration": "5:12"},
            {"id": "1515", "title": "Mere Haath Mein", "duration": "4:12"},
            {"id": "1516", "title": "Shukran Allah", "duration": "5:46"},
            {"id": "1517", "title": "Tum Saath Ho", "duration": "5:41"}
        ]
    },
    {
        "id": "16",
        "name": "Pritam",
        "genres": ["Bollywood", "Fusion", "Folk", "Pop", "Electronic"],
        "songs": [
            {"id": "1601", "title": "Ae Dil Hai Mushkil", "duration": "4:29"},
            {"id": "1602", "title": "Gerua", "duration": "5:08"},
            {"id": "1603", "title": "Kesariya", "duration": "4:28"},
            {"id": "1604", "title": "Channa Mereya", "duration": "5:12"},
            {"id": "1605", "title": "Hawayein", "duration": "4:50"},
            {"id": "1606", "title": "Tum Se Hi", "duration": "5:07"},
            {"id": "1607", "title": "Khairiyat", "duration": "4:40"},
            {"id": "1608", "title": "Kabira", "duration": "4:08"}
        ]
    }
]

